name: Simple Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build my project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo remotely
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.private_repo_path }}
          path: '/home/runner/work/SFA_RUN1_GIT'
          token: ${{ secrets.repo_token }}
      - name: Show hidden files
        run: |
          cd home/
          ls

